
#-----------------------------------------------------------------------
#' Read data from a CosmoSIS format linearized matrix sample file,
#' e.g. a power spectrum file.
#' @param dirname The name of the directory from which we read.
#' @param filename The name of the file we will read.
#' @param quiet  Passed to \code{base::scan}.
#' @return The vector of values.
cosmo.scan <- function(dirname, filename, quiet=TRUE)
{
  scan(file.path(dirname, filename), comment.char = "#", quiet = quiet)
}

#-----------------------------------------------------------------------
#' Create a CosmoSIS 'theory' dataframe from all the named files.
#'
#'
#' Create a CosmoSIS 'theory' dataframe from the 'theory' files
#' generated by a run of CosmoSIS. It is assumed that each file contains
#' a single column of data, and that all the columns are of the same
#' length. This is the standard CosmoSIS output format for a variety of
#' theory calculations. Lines beginning with CosmoSIS comment character
#' "#" are ignored. The names of the columns are determined from the
#' names of the files, by dropping the file extension.
#'
#' @export
#' @param fnames A character vector containing the names of the files to be read.
#' @return A CosmoSIS 'theory' dataframe.
#
# If we change the output of CosmoSIS to make a single file with
# multiple columns, then read.table() would work directly and probably a
# bit more efficiently.
make.theory.dataframe <- function(fnames)
{
  # Scan each file, creating a vector of the right name
  columns <- lapply(fnames, function(n) scan(n, comment.char="#", quiet=TRUE))
  result <- data.frame(columns)
  names(result) <- lapply(fnames, function(n) tools::file_path_sans_ext(basename(n)))
  result
}

#-----------------------------------------------------------------------
#' Create a CosmoSIS matter power dataframe from all the named files.
#'
#' It is assumed the file format is the CosmoSIS format for storing power
#' spectra. Note this format is different from the format used for the storage
#' of scalar parameters.
#' @export
#' @param dirname The name of the directory containing the CosmoSIS power spectrum output.
#' @param type Any value; this value is replicated to fill the \code{type} column of the dataframe.
#' @return A CosmoSIS matter power dataframe. If the directory does not exist, the returned dataframe will be empty.
make.matterpower.dataframe <- function(dirname, type)
{
  # If the directory does not exist, return an empty dataframe.
  if (!file.exists(dirname)) return(data.frame())

  # Scan each file, creating a vector of the right name
  # bind the columns into a dataframe.

  z <- cosmo.scan(dirname, "z.txt")
  k_h <- cosmo.scan(dirname, "k_h.txt")
  p_k <- cosmo.scan(dirname, "p_k.txt")
  nkh <- length(k_h)

  # The p_k array carries the data for a matrix, with 'z' varying slowly
  # and 'k_h' varying rapidly. Thus to build the dataframe, we can rely
  # on the recycling rule to get k_h correct, but have to construct z
  # ourselves.
  dframe <- data.frame( p_k = p_k
                      , k_h = k_h
                      , z = rep(z, each = nkh)
                      )
  dframe$type = type
  dframe
}

#' Create a data frame from CosmoSIS MCMC sampler output.
#'
#' Reads a file in CosmoSIS MCMC sampler output format and creates a data frame
#' from it. Each line in the file corresponds to a sample in the data frame;
#' each column in the file corresponds to a column in the data frame.
#'
#'
#' The columns in a CosmoSIS MCMC data frame are: \describe{
#' \item{loglike}{log-likelihood of the sample.} \item{like}{normalized
#' likelihood of the sample.} \item{\emph{others}}{one column per sampled
#' variable in the MCMC output, named as in the output.} }
#'
#' We expect the first line of the output to contain the names of the
#' parameters, separated by spaces, and with section names separated from
#' parameter names by a double-hyphen.
#'
#' @export
#' @param fname The name of the CosmoSIS MCMC sampler output file to be read.
#' @param burn The length of the burn-in period; these samples are ignored in
#'   making the data frame.
#' @return a CosmoSIS MCMC data frame.
read.cosmosis.mcmc <- function(fname, burn)
{
  d <- read.table(fname)
  # Remove the first 'burn' elements
  d <- d[-c(1:burn),]
  first <- readLines(fname, n = 1)
  first <- sub("#", "", first)           # Remove comment
  parts <- strsplit(first, "\t")[[1]]    # split on tabs
  cols <- sub("[a-zA-Z_]+--", "", parts) # remove leading section names
  cols <- sub("like", "loglike", cols, fixed = TRUE)
  names(d) <- cols
  likes <- exp(d$loglike)
  norm <- sum(likes)
  d$like <- likes/norm
  return(d)
}

#' Create a data frame from CosmoSIS grid sampler output.
#'
#' Reads a file in CosmoSIS grid sampler output format and creates a data frame from it.
